version: '3'
services:
  master:
    hostname: master
    build: master/.
    image: puppet-master
  web:
    hostname: web
    build: agent/.
    image: puppet-agent
    depends_on:
        - master
  db:
    hostname: db
    build: agent/.
    image: puppet-agent
    depends_on:
        - master
