version: '3'
services:
  master:
    hostname: master
    build: master/.
    image: puppet-master
    networks:
        - puppetnet
  web:
    hostname: web
    build: agent/.
    image: puppet-agent
    ports:
        - 80:80
    depends_on:
        - master
    networks:
        - puppetnet
  db:
    hostname: db
    build: agent/.
    image: puppet-agent
    depends_on:
        - master
    networks:
        - puppetnet

networks:
    puppetnet:
